name: CI

on:
  pull_request:
    # types: [review_requested]

jobs:
  Health-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Install NPM dependencies
        run: npm install
      - name: Health Check1 - Test Code
        run: npm run test
      - name: Health Check2 - Compiling
        run: npm run build
